name: 🔨 Build Test

on:
  pull_request:
    paths:
      - '**.go'
      - '**.mod'
  workflow_dispatch:

jobs:
  build:
    name: Test Builds
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    env:
      GOPRIVATE: github.com/peterjmorgan/*
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.26.5

      - name: Check out code
        uses: actions/checkout@v5

      - name: Configure private module access
        run: git config --global "url.https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/.insteadOf" "https://github.com/"

      - name: Verify private module access
        run: go mod download github.com/peterjmorgan/mitmproxy-go

      - name: Build
        run: go build .
        working-directory: cmd/proxify/
      
      - name: Test
        run: go test ./...
      
      # Todo
      # - name: Integration Tests
      #   env:
      #     GH_ACTION: true
      #   run: bash run.sh
      #   working-directory: integration_tests/

      - name: Race Condition Tests
        run: go build -race .
        working-directory: cmd/proxify/

      

      
